project:
  type: book
  output-dir: docs
filters:
  - webr
webr:
  packages: ['palmerpenguins', 'HistData', 'deSolve']
book:
  title: "Quantifying Life"
  author: "Dmitry Kondrashov"
  cover-image: Kondrashov_Comp.jpeg
  favicon: Kondrashov_Comp.jpeg
  twitter-card: true
  search: true
  repo-url: https://github.com/dkon1/quant_life_quarto
  downloads: [pdf, epub]
  site-url: https://dkon1.github.io/quant_life_quarto
  page-navigation: true
  chapters:
    - index.qmd
    - counting.qmd # week 1 preliminaries
    - tutorial1_variables.qmd # coding preliminaries
    - descriptive.qmd # week 1 main point
    - tutorial2_data.qmd # data frames, descriptive stats, and visualization
    - functions.qmd # week 2 functions with basics of linear least squares
    - tutorial3_vectors.qmd # vectors, plotting, function over scatterplot
    - linreg.qmd # week 3, linear regression and residuals, regression to the mean, etc.
    - tutorial4_linreg.qmd # regression concepts and residuals
    - probdist.qmd  # week 4, probability theory, conditional probability and independence
    - independence.qmd # fold into previous chapter
    - tutorial5_randgen.qmd # random number generators, logical tests, conditional probability calculations
    - hypo_test.qmd # week 5: hypothesis testing for independence and errors
    - tutorial6_tables.qmd # bar plots, data tables, chi-squared test and p-values
    - bayes.qmd # week 6: Baysian priors and posteriors
    - tutorial7_functions.qmd # functions
    - lindiff.qmd # week 7: linear difference equations, solutions, and long-term dynamics
    - tutorial8_forloops.qmd # for loops
    - ode_sols.qmd # week 8: ODEs, solutions and graphical analysis
    - tutorial9_odesols.qmd # ode solutions, plotting defining functions
    - graph_odes.qmd # week 9: dependence of stability on parameters
    - references.qmd

bibliography: ql_bibliography.bib

format:
  html:
    theme: materia
  pdf:
    documentclass: scrreprt

editor: visual

